void replace(char* buffer,char* search,char* rpl);
extern unsigned char ord(char x);
extern int length(char *instr);
extern int pos(char key,char* strng);
extern char* copy(char* source,int pos,int length);
extern int val(char* buffer);
extern char* left(char* buffer,int count);
extern char* remspace(char* buffer);
extern char* trailspace(char* buffer);
extern char* upper(char* buffer);
extern char upcase(char in);
